services:
    _defaults:
        autowire: true
        public: true

    NatePage\EasySsm\:
        resource: '../src'
        exclude:
            - '../src/HttpKernel/*'
            - '../src/Services/Aws/Data/*'
            - '../src/Services/Parameters/Data/*'

    Symplify\PackageBuilder\Parameter\ParameterProvider: ~
